### ISSUE TITLE
SetKernelArg error

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/AMBER#6]
Updated the pipeline after I noticed the output branches are merged into master.
Now getting the following error (using fake data):

```
Device: TitanX_demo
Padding: 128 bytes

Beams: 1
Synthesized Beams: 1
Batches: 10
Samples: 25600
Frequency range: 1290 MHz, 1589.8 MHz
Subbands: 1 (300 MHz)
Channels: 1536 (0.195312 MHz)
Zapped Channels: 0
Integration steps: 9
DMs: 1024 (0, 102.3)

terminate called after throwing an instance of 'cl::Error'
  what():  clSetKernelArg
```
gdb says the error is in here: `int cl::Kernel::setArg<cl::Buffer>(unsigned int, cl::Buffer const&) ()`

**Comment by isazi** [comment]
I'll look into it.

**Comment by isazi** [comment]
I don't seem to have the same error. @loostrum can you send me the exact configuration you are using?

**Comment by loostrum** [comment]
Hmm maybe I'm missing something then. Here's the exact command I ran and the conf files.
`TransientSearch -opencl_platform 0 -opencl_device 0 -device_name TitanX_demo -padding_file confs/padding.inc -zapped_channels confs/empty.inc -integration_steps confs/integration_steps_demo.inc -dedispersion_file confs/dedispersion.inc -integration_file confs/integration.inc -snr_file confs/snr.inc -input_bits 8 -output out/demo -dms 1024 -dm_first 0.0 -dm_step 0.1 -threshold 8 -random -width 128 -dm 789 -beams 1 -synthesized_beams 1 -batches 10 -channels 1536 -min_freq 1290 -channel_bandwidth 0.1953125 -samples 25600 -sampling_time 40.96E-6 -compact_results`
[confs.zip](https://github.com/isazi/TransientSearch/files/1037926/confs.zip)

**Comment by isazi** [comment]
Did this work without issues before I merged back the output branch into master?

**Comment by loostrum** [comment]
Yes, I still have the version from before the merge on ARTS0 and there the
exact same conf files + call to TransientSearch do work.

**Comment by isazi** [comment]
OK, the first issue I see is with the configuration files that are missing some of the parameters. I did fix all of the configuration files. Try with them and let me know.

[confs.zip](https://github.com/isazi/TransientSearch/files/1038129/confs.zip)

**Comment by loostrum** [comment]
Thanks for the updated files. I'm still getting the same error. These new config files do work with the old version.

**Comment by isazi** [comment]
There was still a problem with the configuration files I passed you. I am not sure  this is causing your problem, but at least now I can rule it out.
These new configuration files are correct.

[confs.zip](https://github.com/isazi/TransientSearch/files/1038218/confs.zip)

**Comment by loostrum** [comment]
Still the same error, so the config files are not the problem.

**Comment by isazi** [comment]
I am trying to replicate the error using your command line arguments and configuration files, but it keeps working for me.

**Comment by loostrum** [comment]
Then there may be something wrong on Cartesius specifically. I'll install
the newest version separately on ARTS0 and check whether it works there.

**Comment by isazi** [comment]
I am currently installing/tuning/running the pipeline using the scripts from [here](https://github.com/AA-ALERT/artshardware). Still tuning so it'll take time.

**Comment by isazi** [comment]
OK I can now replicate the error, so I should be able to fix it soon enough.

**Comment by isazi** [comment]
I forgot to merge the output branch in SNR. Now merged and everything works.
